### ISSUE TITLE
Selected unfocused entry colors

### ISSUE THREAD

**Issue by spamegg1** [EliverLara/Shades-of-purple-gtk#1]
Hi there :wave: great theme, thanks for the hard work!

I'm using Mint 22 Wilma (Ubuntu 24.04) with Cinnamon (6.2.7).

In Nemo dual-pane view, when a file is selected, and I switch to the other pane, the selected item in the inactive pane gets almost invisible.

Normally, with current pane active:
![Screenshot from 2024-07-28 14-39-24](https://github.com/user-attachments/assets/b095cda4-59c7-4e0f-b20e-907a49be1b3a)

After switching to other pane:
![Screenshot from 2024-07-28 14-38-29](https://github.com/user-attachments/assets/9256e628-1981-4af3-82fa-3085c6b09a33)

These examples are from Nemo's compact view, but they are also present in list view and icon view:
![Screenshot from 2024-07-28 14-41-08](https://github.com/user-attachments/assets/45cbb225-dc81-42be-9a12-86793454cf1e)
![Screenshot from 2024-07-28 14-41-39](https://github.com/user-attachments/assets/bb4a27b8-3d34-4a82-9e6a-6231f0cd31d5)

I tried to find the source of the issue, I think it has something to do with "selected" and "unfocused" but I could not fix it after lots of trial and error.

Issue is present whether "prefer light" or "prefer dark" is selected in Themes / Options.

Any ideas?

**Comment by EliverLara** [comment]
Hi, thanks for reporting! I fixed it in [edb6f6d](https://github.com/EliverLara/Shades-of-purple-gtk/commit/edb6f6d248a2a9c29d7f8743e29f75c4dbfd5462)
